### ISSUE TITLE
Can't bind to 'invalidFileTimeout' since it isn't a known property of 'ng2-file-input'.

### ISSUE THREAD

**Issue by wizquest-labs** [bergben/ng2-file-input#12]
I'm getting this error when using input module as below :

`<ng2-file-input [multiple]="true" [extensions]="allowedExtensions" [invalidFileTimeout]=2000></ng2-file-input>`

Please advise how to modify this property

**Comment by bergben** [comment]
Hey there @wizquest-labs . You have to do it like this:
```<ng2-file-input [multiple]="true" [extensions]="allowedExtensions" [invalid-file-timeout]="2000"></ng2-file-input>```
