### ISSUE TITLE
Not compatible with Angular 5.0

### ISSUE THREAD

**Issue by dreamwisdom** [bergben/ng2-file-input#14]
`ERROR in node_modules/ng2-file-input/dist/src/ng2-file-input.module.d.ts(1,31): error TS2305: Module`
... `/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.`

`OpaqueToken ` was deprecated in angular 4 and removed in angular 5
Replaced with `InjectionToken `

**Comment by bergben** [comment]
Hey @dreamwisdom, thanks for reporting this issue. It has been fixed in 1.0.4
