### ISSUE TITLE
Typo in readme for the specific event's names

### ISSUE THREAD

**Issue by theCrius** [bergben/ng2-file-input#21]
> ### Specific: OnRemoved, OnAdded, OnInvalidDenied, OnCouldNotRemove, OnCouldNotAdd
>     `<ng2-file-input (OnRemoved)="OnRemoved($event)" (OnInvalidDenied)="OnInvalidDenied($event)"></ng2-file-input> `

The "On" part should be lowercase: onAdded, onInvalidDenied, etc etc.
Not a big deal, I noticed while trying to understand why it wasn't working and seeing the onAction was using lowercase.

**Comment by viccsjain** [comment]
Raised PR for this.

**Comment by bergben** [comment]
Thank you guys
