### ISSUE TITLE
dist/FileAPI.flash.swf?r=2.0.21 not found 

### ISSUE THREAD

**Issue by cslgxuchang** [bergben/ng2-file-input#4]
![image](https://user-images.githubusercontent.com/5555434/27215841-b87fea56-52a5-11e7-9592-4c63a9537377.png)

**Comment by cslgxuchang** [comment]
user ng2-file-input,but have a problem with fileapi.false.swf  not found

**Comment by bergben** [comment]
Hey there @cslgxuchang 
You can safely ignore that error, unless you have to support IE9 (currently used by 0.2% worldwide). 
Related is this issue: https://github.com/jellyjs/angular2-file-drop/issues/18 
If you need to support IE9 then please try the solution one guy mentions in the issue linked above.

`angular2-file-drop` is a dependency of ng2-file-input, which uses the `FileAPI`: https://github.com/mailru/FileAPI

**Comment by cslgxuchang** [comment]
@bergben  thanks，my  website need to support IE9，so I will try to use fileapi to solve this problem。
