### ISSUE TITLE
How to reset input?

### ISSUE THREAD

**Issue by Juanperezc** [bergben/ng2-file-input#7]
How can I reset the input and delete the selected items?

**Comment by bergben** [comment]
Hi @Juanperezc ,

this is currently not possible. I could however implement that feature through a service, probably in the next few days. :)

**Comment by kidustiliksew** [comment]
Yes please

**Comment by bergben** [comment]
working on it currently, will release a new version later today :)

**Comment by bergben** [comment]
@Juanperezc  @kidustiliksew  I have just released version `1.0.2` which tackles this issue.  It also introduces some other enhancements such as more specific output events, programmatically adding or removing files and more. Please check out the updated Readme, especially the [Breaking changes in 1.0](https://github.com/bergben/ng2-file-input#breaking-changes-in-10) and [How to reset the file input](https://github.com/bergben/ng2-file-input#reset-the-file-input-or-programatically-add--remove-files). 

Please report back in case that something is not working as expected, closing this ;)
